### ISSUE TITLE
Request for Style Change 

### ISSUE THREAD

**Issue by kevinseabourne** [abielzulio/chatgpt-raycast#9]
Hey Abiel !

Awesome work with the chatGPT extension with Raycast, I am currently using it now with a hotkey map and it is effortlessly amazing. Im making a request to remove or reduce the size of the bottom panel with the date, ID and conversation ID. It does not give the results enough space. And potentially allow the side panel width to be draggable to give the results even more space. Style the code blocks a little better with syntax colors and this extension will be 10/10.

**Comment by abielzulio** [comment]
Hi,

I'll add an option to disable the metadata details view (date, ID, etc) in the extension settings so users can see the answer immersively. The code syntax color is a great feature idea, I'll try to play around with it. The sizeable width is not something I can do because beyond Raycast limitation.

My current focus is publishing the extension to the Raycast store. Once it's published, I'll add the two features that I've mentioned above.

**Comment by abielzulio** [comment]
Closed due to Raycast's extension API. Would consider the code block syntax colors feature in the future.
